parallel-jobs = 3

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
app-name = "Reddit"
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[Photomath]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photomath/"
uptodown-dlurl = "https://photomath.en.uptodown.com/android"
dpi = "120-640dpi"
enabled=falsebuild-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit-Morphe]
app-name = "Reddit"
rv-brand = "Morphe"
build-mode = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
dpi = "120-640dpi"

[Twitter]
enabled = false
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
build-mode = "module"
version = "11.81.0-release.0"
include-stock = "split"

[GooglePhotos]
build-mode = "both"
arch = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
